name: Build and Push Docker Image

on:
  release:
    types:
      - published

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
        # This step already checks out code and install deps
      - name: Setup Node and pnpm
        uses: devhatt/workflows/.github/actions/pnpm-setup@main
        with:
          hasEnvSetup: "false"

      - name: Build
        run: pnpm build

      - name: Test Env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Test Env 2
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_HUB_DEVHATT_LPS_USER }}
          password: ${{ secrets.DOCKER_HUB_DEVHATT_LPS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DEVHATT_LP_REGISTRY_REPOSITORY_NAME }}:latest, ${{ vars.DEVHATT_LP_REGISTRY_REPOSITORY_NAME }}:${{ env.RELEASE_VERSION }}